/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Distribution;

import business.db4O.DatabaseUtils;
import business.distribution.Inventory;
import business.distribution.Order;
import business.ecosystem.Business;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adity
 */
public class ManageOrders extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrders
     */
    
           Business system;
           javax.swing.JSplitPane splitpane;
    public ManageOrders(javax.swing.JSplitPane splitpane,Business system) {
        initComponents();
        this.system = system;
        this.splitpane = splitpane;
        
//        System.out.println("system"+system);
//        
//        Order o  = system.getOrderDirectory().addOrder();
//
//       
//        o.setMedicineName("Remdezvir");
//        o.setSender("da");
//        o.setReciever("asasma@gmail.com");
//        o.setQuantity(5);
//        o.setOrderStatus("Pending");
//        o.setOrderID("2");
//        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtStock = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Medicine Name", "Sender", "Reciever", "Status", "Quantity", "Order ID"
            }
        ));
        jScrollPane1.setViewportView(orderTable);

        jButton1.setText("Assign to Delivery Associate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ready to Deliver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Deny Order");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Avaliable Stock:");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(32, 32, 32)
                .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton1)
                        .addGap(150, 150, 150)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jButton3)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(96, 96, 96))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         int selectedRow = orderTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a row from the Table");
        }
        Order placedOrder = null;
        String orderId = orderTable.getValueAt(selectedRow,5).toString();
        for(Order o : system.getOrderDirectory().getOrder()){
            Order order = o;              
            if(o.getOrderID().equals(orderId)){
                placedOrder = o;
            }
        }
        
        if(placedOrder.getOrderStatus().equals("Work In Progress"))
            JOptionPane.showMessageDialog(null, "Order will be assigned to delivery associate and will be dispatched for delivery");
        else if(placedOrder.getOrderStatus().equals("Pending") || placedOrder.getOrderStatus().equals("Cancelled"))
            placedOrder.setOrderStatus("Work In Progress");
        else{
            JOptionPane.showMessageDialog(null, "Order in progress");
        }
        
        for(Order o : system.getOrderDirectory().getOrder()){
            Order order = o;              
            if(o.getOrderID().equals(placedOrder.getOrderID()) ){
                order.setOrderStatus("Work In Progress");
            }
        }
        populateTable();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
                 int selectedRow = orderTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a row from the Table");
        }
        Order placedOrder = null;
        String orderId = orderTable.getValueAt(selectedRow,5).toString();
        for(Order o : system.getOrderDirectory().getOrder()){
            Order order = o;              
            if(o.getOrderID().equals(orderId) ){
                placedOrder = o;
            }
        }
        
        if(placedOrder.getOrderStatus().equals("Work In Progress"))
            JOptionPane.showMessageDialog(null, "Order cannot be denied");
        else if(placedOrder.getOrderStatus().equals("Pending") || placedOrder.getOrderStatus().equals("Cancelled"))
            placedOrder.setOrderStatus("Canceled");
        else{
            JOptionPane.showMessageDialog(null, "Order in progress");
        }
        
//        for(Order o : system.getOrderDirectory().getOrder()){
//            Order order = o;              
//            if(o.getOrderID() == placedOrder.getOrderID() ){
//                order.setOrderStatus("Canceled");
//            }
//        }
        populateTable();
      

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int selectedRow = orderTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a row from the Table");
        }
        String medicineName  = orderTable.getValueAt(selectedRow,0).toString();
        int count = 0;
        for(Inventory inv : system.getInventoryDirectory().getInventory()){
            if(inv.name.equals(medicineName)){
               count = count + inv.getQuantity();
            }
            else
                JOptionPane.showMessageDialog(null, "The following medicine does not exist");
        }
        
        txtStock.setText(String.valueOf(count));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = orderTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a row from the Table");
        }
        Order placedOrder = null;
        String orderId = orderTable.getValueAt(selectedRow,5).toString();
        for(Order o : system.getOrderDirectory().getOrder()){
            Order order = o;              
            if(o.getOrderID().equals(orderId) ){
                placedOrder = o;
            }
        }
        
        if(placedOrder.getOrderStatus().equals("Work In Progress"))
            JOptionPane.showMessageDialog(null, "Order is already assigned");
        else if( placedOrder.getOrderStatus().equals("Cancelled"))
            JOptionPane.showMessageDialog(null, "Cancelled order cannot be assigned to Delivery Associate");
        else if (placedOrder.getOrderStatus().equals("Completed")){
            JOptionPane.showMessageDialog(null, "Cancelled order cannot be assigned to Delivery Associate");
        }
        else{
                    AssignDeliveryAssociatePanel da = new AssignDeliveryAssociatePanel(splitpane,system,placedOrder);
        splitpane.setRightComponent(da);
        }


        

    }//GEN-LAST:event_jButton1ActionPerformed


       private void populateTable(){
        
         DefaultTableModel model = (DefaultTableModel) orderTable.getModel();
        
        model.setRowCount(0);
            
       
  
            for(Order inv : system.getOrderDirectory().getOrder()) {

                Object[] row = new Object[6];
                row[0] = inv;
    //          row[1] = e.getPatientName();
                row[1] = inv.getSender();
                row[2] = inv.getReciever();
                row[3] = inv.getOrderStatus();
                row[4] = inv.getQuantity();
                row[5] = inv.getOrderID();

                model.addRow(row);           
            }
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderTable;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
