/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.shelter;

import business.ecosystem.Business;
import business.validations.Validations;

/**
 *
 * @author nishi
 */
public class AccountingWorkarea extends javax.swing.JPanel {

    /**
     * Creates new form AccountingWorkarea
     */
    javax.swing.JSplitPane splitpane;
    Validations validations;
    Business system;
    
    public AccountingWorkarea(javax.swing.JSplitPane splitpane, Business system) {
        initComponents();
        this.splitpane = splitpane;
        this.system = system;
   
        this.validations = new Validations();
        lblFunds.setText(String.valueOf(this.system.getCurAmount()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDonations = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblFunds = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(17, 53, 81));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Accounting");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 90));

        txtDonations.setBackground(new java.awt.Color(17, 53, 81));
        txtDonations.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtDonations.setForeground(new java.awt.Color(255, 255, 255));
        txtDonations.setText("Manage Donations");
        txtDonations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonationsActionPerformed(evt);
            }
        });
        add(txtDonations, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 208, 38));

        jButton3.setBackground(new java.awt.Color(17, 53, 81));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Request Funds");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 208, 39));

        jButton1.setBackground(new java.awt.Color(17, 53, 81));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("View Expenses");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 208, 38));

        jLabel3.setText("Current Funds :");
        add(jLabel3);

        lblFunds.setText("0");
        add(lblFunds);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDonationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonationsActionPerformed
        // TODO add your handling code here:
        ManageDonationsWorkarea panel = new ManageDonationsWorkarea(splitpane, system);
        splitpane.setRightComponent(panel);
        
    }//GEN-LAST:event_txtDonationsActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        RequestFunds panel = new RequestFunds(splitpane, system);
        splitpane.setRightComponent(panel);
        
        
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblFunds;
    private javax.swing.JButton txtDonations;
    // End of variables declaration//GEN-END:variables
}
