/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.shelter;

/**
 *
 * @author nishi
 */
public class ShelterManagerWorkarea extends javax.swing.JPanel {

    /**
     * Creates new form ShelterManagerWorkarea
     */
    
    javax.swing.JSplitPane splitpane;
    public ShelterManagerWorkarea(javax.swing.JSplitPane splitpane) {
        initComponents();
        this.splitpane = splitpane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtStaff = new javax.swing.JButton();
        txtDonations = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtShelter = new javax.swing.JButton();

        jLabel1.setText("Shelter Manager");

        txtStaff.setText("Manage Staff");
        txtStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStaffActionPerformed(evt);
            }
        });

        txtDonations.setText("Manage Donations");
        txtDonations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonationsActionPerformed(evt);
            }
        });

        jButton3.setText("Request Funds");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtShelter.setText("View Shelter");
        txtShelter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShelterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jLabel1)
                .addContainerGap(236, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtShelter)
                    .addComponent(jButton3)
                    .addComponent(txtDonations)
                    .addComponent(txtStaff))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addComponent(txtStaff)
                .addGap(18, 18, 18)
                .addComponent(txtDonations)
                .addGap(26, 26, 26)
                .addComponent(jButton3)
                .addGap(29, 29, 29)
                .addComponent(txtShelter)
                .addContainerGap(198, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtShelterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShelterActionPerformed
        // TODO add your handling code here:
        ViewShelterJPanel panel = new ViewShelterJPanel(splitpane);
        splitpane.setRightComponent(panel);
    }//GEN-LAST:event_txtShelterActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ManageStaffWorkarea panel = new ManageStaffWorkarea(splitpane);
        splitpane.setRightComponent(panel);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStaffActionPerformed
        // TODO add your handling code here:
        RequestFunds panel = new RequestFunds(splitpane);
        splitpane.setRightComponent(panel);
    }//GEN-LAST:event_txtStaffActionPerformed

    private void txtDonationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonationsActionPerformed
        // TODO add your handling code here:
        ManageDonationsWorkarea panel = new ManageDonationsWorkarea(splitpane);
        splitpane.setRightComponent(panel);
    }//GEN-LAST:event_txtDonationsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton txtDonations;
    private javax.swing.JButton txtShelter;
    private javax.swing.JButton txtStaff;
    // End of variables declaration//GEN-END:variables
}
