/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Main;

import UI.Distribution.AdminDistribution;
import UI.Distribution.DeliveryAssociateJPanel;
import UI.Distribution.ManageOrders;
import UI.Government.AnalyticsJPanel;
import UI.Government.GovernmentAdmin;
import UI.Government.ManageFundsJPanel;
import UI.Hospitals.DoctorJPanel;
import UI.Hospitals.HospitalAdminJPanel;
import UI.Hospitals.HospitalManagerJPanel;
import UI.Population.PopulationAdmin;
import UI.Population.ReportJPanel;
import UI.shelter.AccountingWorkarea;
import UI.shelter.ManageStaffWorkarea;
import UI.shelter.ShelterAdmin;
import UI.shelter.ShelterManagerWorkarea;
import UI.shelter.StaffWorkarea;
import business.db4O.DatabaseUtils;
import business.ecosystem.Business;
import business.ecosystem.ConfigSystem;
import business.ecosystem.UserAccount;
import business.ecosystem.UserAccountDirectory;
import business.population.Reporter;
import business.validations.Validations;
import java.util.UUID;
import javax.swing.JOptionPane;


/**
 *
 * @author nishi
 */
public class LoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginJPanel
     */
    
    javax.swing.JSplitPane splitpane;
    Validations validations;
    UserAccountDirectory userAccountDirectory;
    Business system;
    DatabaseUtils dB4OUtil = DatabaseUtils.getInstance();
    ConfigSystem config;
    
    public LoginJPanel(javax.swing.JSplitPane splitpane, Business system) {
        initComponents();
        this.splitpane = splitpane;
        this.system = system;

//        this.system = dB4OUtil.retrieveSystem();    
        this.validations = new Validations();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(206, 229, 242));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(17, 53, 81));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(17, 53, 81));
        jLabel2.setText("Email:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(17, 53, 81));
        jLabel3.setText("Password:");

        txtEmail.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N

        txtPassword.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N

        jButton1.setBackground(new java.awt.Color(17, 53, 81));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Zapfino", 1, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Please enter the credentials");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Images/flyingbirds.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Images/pawprints.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(378, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                            .addComponent(txtPassword)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)))
                .addGap(152, 152, 152)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel6)))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(156, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try{
            
            String email = txtEmail.getText();
            String password = txtPassword.getText();
            
            if(!validations.lengthCheck(email) ||!validations.lengthCheck(password))
            {
                JOptionPane.showMessageDialog(this, "Invalid Credentials");
                return;
            }

            
          UserAccount userAccount = system.getUserAccountDirectory().userCheck(email, password);
      
            if(userAccount == null){
                System.out.println("User not found");
                JOptionPane.showMessageDialog(this, "Invalid Credentials");
                return;
                
            } 
            else 
            {
                String role = userAccount.getRole();
                
                system.setCurrentUserEmail(userAccount.getEmail());
                system.setCurrentUserId(userAccount.getUserAccountId());
                system.setCurrentRole(role);
                
//                JOptionPane.showMessageDialog(this, "role is "+role);
                if(role.equals("Doctor")){
                                            DoctorJPanel panel = new DoctorJPanel(splitpane, system);
                    splitpane.setRightComponent(panel);
                }
                else if(role.equals("ShelterStaff")){
                    StaffWorkarea panel = new StaffWorkarea(splitpane, system);
                    splitpane.setRightComponent(panel);
                }
                else if(role.equals("Accountant")){
                    AccountingWorkarea panel = new AccountingWorkarea(splitpane, system);
                    splitpane.setRightComponent(panel);
                }
                else if(role.equals("Reporter")){
                    ReportJPanel panel = new ReportJPanel(splitpane, system);
                    splitpane.setRightComponent(panel);
                    
                }
                else if(role.equals("ShelterManager")){
                    ShelterManagerWorkarea panel = new ShelterManagerWorkarea(splitpane, system);
                    splitpane.setRightComponent(panel);
                }
                else if(role.equals("ShelterAdmin")){
                    ShelterAdmin panel = new ShelterAdmin(splitpane, system);
                    splitpane.setRightComponent(panel);
                }
                else if(role.equals("HospitalAdmin")){
                    HospitalAdminJPanel panel = new HospitalAdminJPanel(splitpane, system);
                    splitpane.setRightComponent(panel);
                }
                else if(role.equals("DistributionAdmin")){
                                        AdminDistribution panel = new AdminDistribution(splitpane,system);
                    splitpane.setRightComponent(panel);
                }
                else if(role.equals("GovernmentAdmin")){
                    GovernmentAdmin panel = new GovernmentAdmin(splitpane, system);
                    splitpane.setRightComponent(panel);
                }
                else if(role.equals("AnalyticsManager")){
                    AnalyticsJPanel panel = new AnalyticsJPanel(splitpane, system);
                    splitpane.setRightComponent(panel);
                }
                else if(role.equals("Overseer")){
                    ManageFundsJPanel panel = new ManageFundsJPanel(splitpane, system);
                    splitpane.setRightComponent(panel);
                }
                                else if(role.equals("DeliveryAssociate")){
                    DeliveryAssociateJPanel panel = new DeliveryAssociateJPanel(splitpane, system,userAccount);
                    splitpane.setRightComponent(panel);
                }
                else if(role.equals("HospitalManager")){
                    HospitalManagerJPanel panel = new HospitalManagerJPanel(splitpane, system);
                    splitpane.setRightComponent(panel);
                }
                else if(role.equals("PopulationAdmin")){
                    PopulationAdmin panel = new PopulationAdmin(splitpane, system);
                    splitpane.setRightComponent(panel);
                }
                                else if(role.equals("DistributionManager")){
                    ManageOrders panel = new ManageOrders(splitpane, system);
                    splitpane.setRightComponent(panel);
                }

                
                
                
            }

            
        }
        catch(Exception e){
            System.out.println("Login Error, try again "+e);
            JOptionPane.showMessageDialog(this, "Login Error, try again");
            return;
        }
           
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
