/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Hospital;

/**
 *
 * @author sinchanakumar
 */
public class ManageDoctorsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDoctorsJPanel
     */
    public ManageDoctorsJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        medicalIcon = new javax.swing.JLabel();
        DocID = new javax.swing.JLabel();
        txtDocID = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        txtDocID1 = new javax.swing.JTextField();
        name1 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        txtDocID2 = new javax.swing.JTextField();
        txtDocID3 = new javax.swing.JTextField();
        name3 = new javax.swing.JLabel();
        name4 = new javax.swing.JLabel();
        name5 = new javax.swing.JLabel();
        name6 = new javax.swing.JLabel();
        txtAge = new javax.swing.JSpinner();
        drpGender = new javax.swing.JComboBox<>();
        txtDocID4 = new javax.swing.JTextField();
        txtDocID5 = new javax.swing.JTextField();
        name7 = new javax.swing.JLabel();
        name8 = new javax.swing.JLabel();
        txtDocID6 = new javax.swing.JTextField();
        txtDocID7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        DocID1 = new javax.swing.JLabel();
        txtDocID8 = new javax.swing.JTextField();
        name9 = new javax.swing.JLabel();
        txtDocID9 = new javax.swing.JTextField();
        txtDocID10 = new javax.swing.JTextField();
        name10 = new javax.swing.JLabel();
        name11 = new javax.swing.JLabel();
        name12 = new javax.swing.JLabel();
        name13 = new javax.swing.JLabel();
        name14 = new javax.swing.JLabel();
        name15 = new javax.swing.JLabel();
        name16 = new javax.swing.JLabel();
        name17 = new javax.swing.JLabel();
        txtDocID11 = new javax.swing.JTextField();
        txtAge1 = new javax.swing.JSpinner();
        drpGender1 = new javax.swing.JComboBox<>();
        txtDocID12 = new javax.swing.JTextField();
        txtDocID13 = new javax.swing.JTextField();
        txtDocID14 = new javax.swing.JTextField();
        txtDocID15 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(17, 53, 81));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Doctors");

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(17, 53, 81));
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jPanel2.setLayout(null);

        medicalIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Images/medicalLogo.png"))); // NOI18N
        medicalIcon.setText("jLabel3");
        jPanel2.add(medicalIcon);
        medicalIcon.setBounds(852, 135, 192, 377);

        DocID.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        DocID.setForeground(new java.awt.Color(1, 77, 78));
        DocID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DocID.setText("Doctor ID:");
        jPanel2.add(DocID);
        DocID.setBounds(239, 105, 133, 23);
        jPanel2.add(txtDocID);
        txtDocID.setBounds(390, 105, 225, 22);

        name.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        name.setForeground(new java.awt.Color(1, 77, 78));
        name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        name.setText("Name:");
        jPanel2.add(name);
        name.setBounds(239, 146, 133, 23);
        jPanel2.add(txtDocID1);
        txtDocID1.setBounds(390, 146, 225, 22);

        name1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        name1.setForeground(new java.awt.Color(1, 77, 78));
        name1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        name1.setText("Username:");
        jPanel2.add(name1);
        name1.setBounds(239, 187, 133, 23);

        name2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        name2.setForeground(new java.awt.Color(1, 77, 78));
        name2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        name2.setText("Password:");
        jPanel2.add(name2);
        name2.setBounds(239, 228, 133, 23);
        jPanel2.add(txtDocID2);
        txtDocID2.setBounds(390, 187, 225, 22);
        jPanel2.add(txtDocID3);
        txtDocID3.setBounds(390, 228, 225, 22);

        name3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        name3.setForeground(new java.awt.Color(1, 77, 78));
        name3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        name3.setText("Age:");
        jPanel2.add(name3);
        name3.setBounds(239, 271, 133, 23);

        name4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        name4.setForeground(new java.awt.Color(1, 77, 78));
        name4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        name4.setText("Gender:");
        jPanel2.add(name4);
        name4.setBounds(239, 315, 133, 23);

        name5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        name5.setForeground(new java.awt.Color(1, 77, 78));
        name5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        name5.setText("Specilization:");
        jPanel2.add(name5);
        name5.setBounds(239, 351, 133, 23);

        name6.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        name6.setForeground(new java.awt.Color(1, 77, 78));
        name6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        name6.setText("Years of Experience:");
        jPanel2.add(name6);
        name6.setBounds(239, 386, 126, 23);

        txtAge.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtAge.setModel(new javax.swing.SpinnerNumberModel(18, 18, 60, 1));
        jPanel2.add(txtAge);
        txtAge.setBounds(390, 269, 64, 26);

        drpGender.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        drpGender.setForeground(new java.awt.Color(1, 77, 78));
        drpGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        drpGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drpGenderActionPerformed(evt);
            }
        });
        jPanel2.add(drpGender);
        drpGender.setBounds(390, 313, 82, 26);
        jPanel2.add(txtDocID4);
        txtDocID4.setBounds(390, 351, 225, 22);
        jPanel2.add(txtDocID5);
        txtDocID5.setBounds(390, 386, 225, 22);

        name7.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        name7.setForeground(new java.awt.Color(1, 77, 78));
        name7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        name7.setText("Phone No:");
        jPanel2.add(name7);
        name7.setBounds(239, 427, 133, 23);

        name8.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        name8.setForeground(new java.awt.Color(1, 77, 78));
        name8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        name8.setText("Email:");
        jPanel2.add(name8);
        name8.setBounds(239, 468, 133, 23);
        jPanel2.add(txtDocID6);
        txtDocID6.setBounds(390, 427, 225, 22);
        jPanel2.add(txtDocID7);
        txtDocID7.setBounds(390, 468, 225, 22);

        jButton1.setBackground(new java.awt.Color(17, 53, 81));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("  Register");
        jPanel2.add(jButton1);
        jButton1.setBounds(390, 520, 220, 30);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(17, 53, 81));
        jButton3.setText("Reset");
        jPanel2.add(jButton3);
        jButton3.setBounds(230, 520, 110, 30);

        jTabbedPane1.addTab("Create Doctor", jPanel2);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Images/medicalLogo.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        DocID1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        DocID1.setForeground(new java.awt.Color(1, 77, 78));
        DocID1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DocID1.setText("Doctor ID:");

        name9.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        name9.setForeground(new java.awt.Color(1, 77, 78));
        name9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        name9.setText("Name:");

        name10.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        name10.setForeground(new java.awt.Color(1, 77, 78));
        name10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        name10.setText("Username:");

        name11.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        name11.setForeground(new java.awt.Color(1, 77, 78));
        name11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        name11.setText("Password:");

        name12.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        name12.setForeground(new java.awt.Color(1, 77, 78));
        name12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        name12.setText("Age:");

        name13.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        name13.setForeground(new java.awt.Color(1, 77, 78));
        name13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        name13.setText("Gender:");

        name14.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        name14.setForeground(new java.awt.Color(1, 77, 78));
        name14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        name14.setText("Specilization:");

        name15.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        name15.setForeground(new java.awt.Color(1, 77, 78));
        name15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        name15.setText("Years of Experience:");

        name16.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        name16.setForeground(new java.awt.Color(1, 77, 78));
        name16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        name16.setText("Phone No:");

        name17.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        name17.setForeground(new java.awt.Color(1, 77, 78));
        name17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        name17.setText("Email:");

        txtAge1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtAge1.setModel(new javax.swing.SpinnerNumberModel(18, 18, 60, 1));

        drpGender1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        drpGender1.setForeground(new java.awt.Color(1, 77, 78));
        drpGender1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        drpGender1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drpGender1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(17, 53, 81));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update");

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTable1.setForeground(new java.awt.Color(17, 53, 81));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Doctor ID", "Name", "Specializaition", "Years of Experience"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnView.setBackground(new java.awt.Color(17, 53, 81));
        btnView.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setText("View");

        btnDelete.setBackground(new java.awt.Color(138, 10, 20));
        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DocID1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name9, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name10, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name11, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name12, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name13, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name14, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name15)
                    .addComponent(name16, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name17, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDocID8, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDocID9, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDocID10, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDocID11, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAge1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drpGender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDocID12, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDocID13, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDocID14, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDocID15, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(561, 561, 561)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(DocID1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(name9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(name10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(name11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(name12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)
                                        .addComponent(name13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(13, 13, 13)
                                        .addComponent(name14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(name15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(name16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(name17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtDocID8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDocID9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDocID10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDocID11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtAge1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(drpGender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(txtDocID12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(txtDocID13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDocID14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDocID15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jTabbedPane1.addTab("View Doctor", jPanel3);

        btnBack.setBackground(new java.awt.Color(17, 53, 81));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1359, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel1);
        jPanel1.setBounds(0, 0, 1466, 1001);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void drpGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drpGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drpGenderActionPerformed

    private void drpGender1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drpGender1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drpGender1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DocID;
    private javax.swing.JLabel DocID1;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> drpGender;
    private javax.swing.JComboBox<String> drpGender1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel medicalIcon;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name10;
    private javax.swing.JLabel name11;
    private javax.swing.JLabel name12;
    private javax.swing.JLabel name13;
    private javax.swing.JLabel name14;
    private javax.swing.JLabel name15;
    private javax.swing.JLabel name16;
    private javax.swing.JLabel name17;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JLabel name5;
    private javax.swing.JLabel name6;
    private javax.swing.JLabel name7;
    private javax.swing.JLabel name8;
    private javax.swing.JLabel name9;
    private javax.swing.JSpinner txtAge;
    private javax.swing.JSpinner txtAge1;
    private javax.swing.JTextField txtDocID;
    private javax.swing.JTextField txtDocID1;
    private javax.swing.JTextField txtDocID10;
    private javax.swing.JTextField txtDocID11;
    private javax.swing.JTextField txtDocID12;
    private javax.swing.JTextField txtDocID13;
    private javax.swing.JTextField txtDocID14;
    private javax.swing.JTextField txtDocID15;
    private javax.swing.JTextField txtDocID2;
    private javax.swing.JTextField txtDocID3;
    private javax.swing.JTextField txtDocID4;
    private javax.swing.JTextField txtDocID5;
    private javax.swing.JTextField txtDocID6;
    private javax.swing.JTextField txtDocID7;
    private javax.swing.JTextField txtDocID8;
    private javax.swing.JTextField txtDocID9;
    // End of variables declaration//GEN-END:variables
}
